"""Builds landing-page X-ray assets from the local NIH bbox subset.

Run from the repo root:  python scripts/make_hero_assets.py
Writes frontend/public/xray/<Label>.webp and frontend/src/data/xrays.ts
"""
import csv
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
BBOX_CSV = ROOT / "data" / "bbox_eval" / "BBox_List_2017.csv"
IMG_DIR = ROOT / "data" / "bbox_eval" / "bbox_images"
OUT_IMG = ROOT / "frontend" / "public" / "xray"
OUT_TS = ROOT / "frontend" / "src" / "data" / "xrays.ts"

SIZE = 900
ORIGINAL = 1024.0
ORDER = [
    "Cardiomegaly", "Effusion", "Pneumothorax", "Atelectasis",
    "Mass", "Pneumonia", "Infiltration", "Nodule",
]


def main() -> None:
    OUT_IMG.mkdir(parents=True, exist_ok=True)
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)

    by_label: dict[str, list[tuple[str, float, float, float, float]]] = {}
    with open(BBOX_CSV, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)  # header
        for row in reader:
            if len(row) < 6:
                continue
            name, label = row[0].strip(), row[1].strip()
            if label == "Infiltrate":
                label = "Infiltration"
            try:
                x, y, w, h = (float(v) for v in row[2:6])
            except ValueError:
                continue
            if not (IMG_DIR / name).exists():
                continue
            by_label.setdefault(label, []).append((name, x, y, w, h))

    entries = []
    for label in ORDER:
        rows = sorted(by_label.get(label, []), key=lambda r: r[3] * r[4])
        if not rows:
            print(f"skip {label}: no annotated images found")
            continue
        name, x, y, w, h = rows[len(rows) // 2]  # median-sized box
        im = Image.open(IMG_DIR / name).convert("L")
        im = ImageOps.autocontrast(im, cutoff=0.5)
        im = im.resize((SIZE, SIZE), Image.LANCZOS)
        im.save(OUT_IMG / f"{label}.webp", "WEBP", quality=78)
        box = {k: round(v / ORIGINAL * 100, 1) for k, v in zip("xywh", (x, y, w, h))}
        entries.append((label, box))
        print(f"ok   {label:<13} {name}")

    lines = [
        "// Generated by scripts/make_hero_assets.py. Boxes are NIH ground truth, in % of the image.",
        "export type Xray = {",
        "  label: string;",
        "  src: string;",
        "  box: { x: number; y: number; w: number; h: number };",
        "};",
        "",
        "export const XRAYS: Xray[] = [",
    ]
    for label, b in entries:
        lines.append(
            f'  {{ label: "{label}", src: "/xray/{label}.webp", '
            f'box: {{ x: {b["x"]}, y: {b["y"]}, w: {b["w"]}, h: {b["h"]} }} }},'
        )
    lines.append("];")
    OUT_TS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(entries)} images + {OUT_TS}")


if __name__ == "__main__":
    main()